services:
  - type: web
    name: realm-verify-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: LLM_API_KEY
        sync: false
      - key: LLM_BASE_URL
        value: https://api.groq.com/openai/v1
      - key: LLM_MODEL
        value: llama-3.3-70b-versatile
      - key: MONGO_USERNAME
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: MONGO_CLUSTER
        value: realm1.litipri.mongodb.net
